### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by NishanthVAnand** [Alexis816/sarsa-lambda-frozen-lake#1]
I don't think your code is working. average reward over the past 100 episodes is less than 0.4. Please add supporting graphs for the results.

**Comment by Alexis816** [comment]
Hello, thank you for reporting this! I didn't know the average reward had to be greater than 0.4. I think it should be fixed now, I added a decay for epsilon so that the agent explore more in the first episodes and then acts more and more greedily. I also added a graph with a moving average on the first returns, it is now greater than 0.4 for the last episodes.
